language: objective-c
osx_image: xcode10.3
xcode_workspace: NLocalizationManager.xcworkspace # path to your xcodeproj folder
xcode_scheme: NLocalizationManager
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
branches:
  only:
  - master
before_install:
    - pod install
after_success:
    - gem install jazzy
    - make docs
script:
    - echo "Skipping building on Travis, we're building for docs ourselves."
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: jazzy_docs
  keep_history: true
  on:
    branch: master
